import "@blog/styles/globals.scss";

import { type Metadata } from "next";
import { TRPCReactProvider } from "@blog/trpc/react";
import { HydrateClient } from "@blog/trpc/server";
import { DARK_THEME } from "@blog/components/theme/types";
import type { PropsWithChildren } from "react";
import { I18nInit } from "@blog/i18n/ClientInit";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en" data-theme={DARK_THEME}>
      <body className="bg-base-100 text-base-content">
        <TRPCReactProvider>
          <HydrateClient>
            <I18nInit>
              {children}
            </I18nInit>
          </HydrateClient>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
