import "@blog/styles/globals.scss";

import {type Metadata} from "next";
import {TRPCReactProvider} from "@blog/trpc/react";
import {mainThemes, themeDataKey} from "@blog/components/theme/constants";
import {HydrateClient} from "@blog/trpc/server";
import {ThemeProvider} from "next-themes";
import type {PropsWithChildren} from "react";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({children,}: Readonly<PropsWithChildren>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body>
        <TRPCReactProvider>
            <HydrateClient>
                <ThemeProvider storageKey={themeDataKey} themes={mainThemes}>
                    {children}
                </ThemeProvider>
            </HydrateClient>
        </TRPCReactProvider>
        </body>
        </html>
    );
}
